1 scoring repository
asiaKaplanska/GuessingGame pull request #2
Opened 2023-06-09 20:13 UTC by asiaKaplanska

2023-06-10 08:19 UTC, gerardolenski requested changes

2023-06-10 08:19 UTC, gerardolenski commented on src/main/java/org/asia/game/result/JsonFileRepository.java
> +import static org.asia.game.Config.DIRECTORY_PATH;
It is not good to use static values here. How will you test this class if the directory is constant? During tests, you should work on temporary files eg. by using `Files:createTempFile`

To fix this you should:
- add a field `private final Path repositoryPath` to this class
- inject the correct path during instantiation by your factory
- in test you can inject then the temporary created file

2023-06-10 08:19 UTC, gerardolenski commented on src/main/java/org/asia/game/result/JsonFileRepository.java
> +    GameUI gameUI = new GameUI();
Oh no no. Why? You broke the single responsibility principle. There is no reason to call the user interface by the repository. Please remove it from this class and access the user interface in `GameLoop`. [ofc do the same in `InMemoryRepository`]

BTW. If your intention was to add some application logs when you work with the repository, then you need to integrate with logging API. We can do it in separate task.

2023-06-10 08:19 UTC, gerardolenski commented on src/main/java/org/asia/game/result/JsonFileRepository.java
> +        } catch (JsonProcessingException ignored) {}
We never should ignore the exception. Please introduce your own runtime exception e.g. `GameReporitoryProcessingException` and throw it whenever you meet an unsolvable condition.

2023-06-10 08:19 UTC, gerardolenski commented on src/main/java/org/asia/game/result/JsonFileRepository.java
> +        try {
General comment: 
- please format the code correctly (I can find several not formatted code blocks). `CRTL +ALT + L` is your friend ;P
- please youse `var` keyword - in most places there is no reason to duplicate class when variable is initialized

2023-06-10 08:19 UTC, gerardolenski commented on src/main/java/org/asia/game/result/JsonFileRepository.java
> +            FileOutputStream fileOutputStream =
This is a BUG. You do not work correctly with IO stream. The stream should be always correctly closed. In this case you work with the `Autocloseable` resource, so the best way is to use `try-with-resources` statement. 

See: https://www.baeldung.com/java-try-with-resources

BTW: I don't think you need the OutputStreamWriter here. Why not just write bytes to the file output stream directly?
See: https://www.baeldung.com/java-outputstream

2023-06-10 08:19 UTC, gerardolenski commented on src/main/java/org/asia/game/result/JsonFileRepository.java
> +class JsonFileRepository implements GameResultRepository {
please test this class

2023-06-10 08:19 UTC, gerardolenski commented on src/main/java/org/asia/game/result/InMemoryRepository.java
> +class InMemoryRepository implements GameResultRepository{
please test this class

2023-06-10 08:19 UTC, gerardolenski commented on src/main/java/org/asia/game/result/GameResultRepositoryFactory.java
> +        this.destination = destination;
Please handle correctly the null parameter - we should throw an exception if someone passes `null` here instead of the correct enum.

2023-06-10 10:36 UTC, asiaKaplanska commented on src/main/java/org/asia/game/result/JsonFileRepository.java
> +        } catch (JsonProcessingException ignored) {}
Question to line 46: Should I also use my custom exception in this case?

2023-06-15 17:18 UTC, gerardolenski commented on src/main/java/org/asia/game/result/JsonFileRepository.java
> +
Formatting - I see you tend to put an empty line directly at the beginning of the method body. Generally, we don't do that ;)

2023-06-15 17:18 UTC, gerardolenski commented on src/main/java/org/asia/game/result/JsonFileRepository.java
> +        var mapper = new ObjectMapper().registerModule(new JavaTimeModule());
The ObjectMapper is thread save and can be reused. You could extract it to private constant.

2023-06-15 17:18 UTC, gerardolenski commented on src/main/java/org/asia/game/result/JsonFileRepository.java
> +            System.out.println(json);
What is the intention of this `println`? Did you do this accidentally or you just wanted to add some logs?

2023-06-15 17:18 UTC, gerardolenski commented on src/main/java/org/asia/game/result/JsonFileRepository.java
> +                Files.createDirectory(parentPath);
1. So here you create just the last directory of a given path. Is that what you want? Or maybe you wanted to create all the missing directories (see: `Files.createDirectories`)? Just asking - not sure what you wanted to do here ;)
2. Formatting: The good practice is to add static imports to utility classes (**BUT only when the method name is informative enough**). So instead of `Files.createDirectory()` or `Files.exists` would be just `createDirectory()` and `exists()`

2023-06-15 17:18 UTC, gerardolenski commented on src/main/java/org/asia/game/result/JsonFileRepository.java
> +        try {
Basically, you divided quite well the code to private methods (good job). But also here you could do it **to avoid try in try and increase code readability**.

If you would add a method eg: `private String convertToJson(GameResult result)` then entire logic will be simple as:
```
@Override
    public void saveGameResult(GameResult gameResult) throws GameRepositoryProcessingException {
        var json = convertToJson(gameResult);
        saveGameResultToFile(json);
    }
```

2023-06-15 17:18 UTC, gerardolenski commented on src/main/java/org/asia/game/result/JsonFileRepository.java
> +            var records = loadResultsFile().split(System.lineSeparator());
1. `System.lineSeparator` can be extracted to constant. And please use this constant everywhere in this class.
2. There is no need to have `var records = loadResultsFile().split(System.lineSeparator());` in try statement. Am I right?
3. And if 2 will be done, then the entire try statement could be extracted to another private method, e.g.  `private List<GameResult> convertFromJson(String[] json)`. So the whole logic would be simple as:
```
@Override
    public List<GameResult> getAllGameResults() throws GameRepositoryProcessingException {
        var records = loadResultsFile().split(System.lineSeparator());
        return convertFromJson(records);
    }
```

2023-06-15 17:18 UTC, gerardolenski commented on src/main/java/org/asia/game/result/JsonFileRepository.java
> +        try (var reader = Files.newBufferedReader(repositoryFilePath)) {
Well. You could simplify it by using `Files.readAllLines` or `Files.readString` ;)

2023-06-15 17:25 UTC, gerardolenski commented on src/test/java/org/asia/game/result/JsonFileRepositoryTest.java
> +    @DisplayName("Should correctly add new game result to list of results [positive]")
So this is a case when you add the first and only one entry to repository - the display name informs about the different use case. 

You should also add another test, where you will add result to existing entries. And check if repository still contains old content  and new added.

2023-06-15 17:39 UTC, gerardolenski commented on src/main/java/org/asia/game/result/GameResultRepositoryFactory.java
> +        } else throw new IllegalArgumentException();
The good practice is to add the message to the exception

2023-06-15 17:39 UTC, gerardolenski commented on src/main/java/org/asia/game/result/GameResultRepositoryFactory.java
> +                    yield new JsonFileRepository(Path.of(Config.FILE_PATH));
1. So why Config.FILE_PATH cannot be defined as `Path` immediately instead of `String`.
2. Please add static import to have just `FILE_PATH` and not `Config.FILE_PATH` ;)

2023-06-15 17:39 UTC, gerardolenski commented on src/main/java/org/asia/game/result/InMemoryRepository.java
> +class InMemoryRepository implements GameResultRepository{
What an ugly unformatted class definition :D

2023-06-17 06:06 UTC, gerardolenski reviewed
Good job. Just the last hints and one bug ;)

2023-06-17 06:06 UTC, gerardolenski commented on src/main/java/org/asia/game/result/JsonFileRepository.java
> +    private final ObjectMapper mapper = new ObjectMapper().registerModule(new JavaTimeModule());
Basically, `mapper` and `lineSeparator` would be declared as constants:

```
class JsonFileRepository implements GameResultRepository {

    private static final ObjectMapper MAPPER = new ObjectMapper().registerModule(new JavaTimeModule());
    private static final String LINE_SEPARATOR = lineSeparator();

    private final Path repositoryFilePath;
```

2023-06-17 06:06 UTC, gerardolenski commented on src/main/java/org/asia/game/result/JsonFileRepository.java
> +        byte[] bytes = gameResult.getBytes();
There is one possible bug here. You convert string to byte array without implicitly setting the charset. So the default 
 system charset will be used. See:
 
![image](https://github.com/asiaKaplanska/GuessingGame/assets/31597546/10400519-6eec-4150-bac0-7dc17136b38a)

And on the other hand, when you read the file you use UTF-8 charset. See:

![image](https://github.com/asiaKaplanska/GuessingGame/assets/31597546/223f28c9-8201-4dc4-a45d-ca8596fb59ca)

Do you understand the possible impact? Basically, you should always take control of the desired encoding.

2023-06-17 06:06 UTC, gerardolenski commented on src/main/java/org/asia/game/result/JsonFileRepository.java
> +            return Files.readAllLines(repositoryFilePath);
static import pls

2023-06-17 06:06 UTC, gerardolenski commented on src/test/java/org/asia/game/result/JsonFileRepositoryTest.java
> +    JsonFileRepository jsonFileRepository;
Slight refactor - you do not need this field, right?

2023-06-17 06:06 UTC, gerardolenski commented on src/test/java/org/asia/game/result/JsonFileRepositoryTest.java
> +        jsonFileRepository = new JsonFileRepository(tempPath);
Hint: commonly we use the term "system under test": `sut`. So it would be nice to declare this object in this way:

```
var sut = new JsonFileRepository(tempPath);
```

It just shows what do you test in this unit.

2023-06-19 13:54 UTC, gerardolenski approved these changes

2023-06-19 13:56 UTC, merged